#!/bin/bash
shopt -s expand_aliases
alias ccs="cast send --private-key $PRIVATE_KEY $CONTRACT_ADDRESS"
alias cca="cast call $CONTRACT_ADDRESS"
ccs 'contribute()' --value 0.0009ether
cca 'getContributions()(uint)'
ccs --value 0.0009ether
ccs 'withdraw()'
